services:
  livon-be:
    container_name: livon-be-dev
    build:
      context: ../LivOnBack
      dockerfile: Dockerfile
    ports:
      - "8082:8081" # 외부:내부 포트
    volumes:
      - ../LivOnBack/src:/app/src
      - ../keys:/app/keys:ro
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GCP_KEY_FILE=/app/keys/livon-477113-1cbd80f7207d.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-dev-net

  livon-fe:
    container_name: livon-fe-dev
    build:
      context: ../LivOnFront/web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-dev-net

  nginx:
    container_name: nginx-dev
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/livon/downloads:/downloads
    ports:
      - "8443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - livon-fe
    networks:
      - livon-dev-net

networks:
  livon-dev-net:
    external: true

volumes:
  apk_storage:
    external: true
