services:
  livon-be:
    container_name: livon-be-prod
    build:
      context: ../LivOnBack
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    # volumes:
    #   - ../keys:/app/keys:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GCP_KEY_FILE=/app/keys/livon-477113-1cbd80f7207d.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-prod-net

  livon-fe:
    container_name: livon-fe-prod
    build:
      context: ../LivOnFront/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-prod-net

  nginx:
    container_name: nginx-prod
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/livon/downloads:/downloads
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - livon-fe
    networks:
      - livon-prod-net

networks:
  livon-prod-net:
    external: true

volumes:
  apk_storage:
    external: true
