services:
  livon-be:
    container_name: livon-be-prod
    build:
      context: ../LivOnBack
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    # volumes:
    #  - ../LivOnBack/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-prod-net

  livon-fe:
    container_name: livon-fe-prod
    build:
      context: ../LivOnFront/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - livon-prod-net

  nginx:
    container_name: nginx-prod
    network_mode: host
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/livon/downloads:/downloads
    # ports:
    #   - "80:80"
    #   - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - livon-fe
    networks:
      - livon-prod-net

networks:
  livon-prod-net:
    external: true

volumes:
  apk_storage:
    external: true
